// adapters/contract/zod/renderer.ts —— Zod 契约渲染器
// P0-2 产出：把契约元模型 (YAML) 渲染为 Zod schema (TypeScript)。
//
// 覆盖类型映射：
//   string → z.string()
//   number → z.number().int() (整数) / z.number() (默认)
//   boolean → z.boolean()
//   uuid → z.string().uuid()
//   datetime → z.string().datetime()
//   email → z.string().email()
//   enum → z.enum([...])
//   array → z.array(items)
//   ref → 引用另一 schema 名

import { readFileSync, readdirSync } from 'node:fs';
import { load as parseYaml } from 'js-yaml';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import type {
  ContractSchemaMeta,
  ContractFieldMeta,
  RenderContractInput,
  RenderContractResult,
  WriteOp,
  Confidence,
} from '../../../spi/adapter.js';

interface FieldMetaInternal extends ContractFieldMeta {
  /** enum_values_ref：引用另一 enum schema 的 enum 值 */
  enum_values_ref?: string;
  /** ref：引用另一 object schema */
  ref?: string;
}

interface SchemaMetaInternal extends ContractSchemaMeta {
  fields?: FieldMetaInternal[];
}

interface MetaFile {
  schemas: SchemaMetaInternal[];
}

export async function renderContract(input: RenderContractInput): Promise<RenderContractResult> {
  // 元模型预加载（同一目录下的所有 *.meta.yaml）
  const metaFiles = findMetaFiles(input.out_dir);
  const allSchemas = new Map<string, SchemaMetaInternal>();
  for (const f of metaFiles) {
    const parsed = parseYaml(readFileSync(f, 'utf8')) as MetaFile;
    for (const s of parsed.schemas ?? []) {
      allSchemas.set(s.name, s);
    }
  }
  // 也接收 input.schemas
  for (const s of input.schemas as SchemaMetaInternal[]) {
    allSchemas.set(s.name, s);
  }

  const writes: WriteOp[] = [];
  const unsupported: string[] = [];
  let confidence: Confidence = 1;

  // 渲染每个 schema 为一个 .ts 文件
  for (const schema of allSchemas.values()) {
    const { code, unsupported: schemaUnsupported, confidence: schemaConf } = renderSchema(schema, allSchemas);
    if (schemaUnsupported.length) unsupported.push(...schemaUnsupported);
    confidence = Math.min(confidence, schemaConf);

    writes.push({
      path: join(input.out_dir, 'rendered', 'zod', `${schema.name}.ts`),
      content: code,
      is_new: true,
      reason: `P0-2 Zod 渲染：${schema.name}`,
    });
  }

  // 生成 index.ts 聚合导出
  const indexCode = renderIndex([...allSchemas.keys()]);
  writes.push({
    path: join(input.out_dir, 'rendered', 'zod', 'index.ts'),
    content: indexCode,
    is_new: true,
    reason: 'P0-2 Zod 渲染：聚合导出',
  });

  return {
    writes,
    confidence,
    unsupported_types: [...new Set(unsupported)],
  };
}

function renderSchema(
  schema: SchemaMetaInternal,
  all: Map<string, SchemaMetaInternal>,
): { code: string; unsupported: string[]; confidence: number } {
  const lines: string[] = [];
  const unsupported: string[] = [];
  let confidence = 1;

  // 头部注释
  lines.push(`// AUTO-GENERATED by Zod renderer. DO NOT EDIT.`);
  lines.push(`// Source: contract meta model (${schema.name})`);
  if (schema.description) {
    for (const line of schema.description.split('\n')) {
      lines.push(`// ${line}`);
    }
  }
  lines.push('');
  lines.push(`import { z } from 'zod';`);
  lines.push('');

  // 依赖的 schema 引用
  const deps = collectDeps(schema, all);
  if (deps.size > 0) {
    for (const dep of deps) {
      lines.push(`import { ${dep}Schema } from './${dep}';`);
    }
    lines.push('');
  }

  const name = `${schema.name}Schema`;

  if (schema.kind === 'enum') {
    if (!schema.enum_values?.length) {
      lines.push(`export const ${name} = z.enum([]); // ERROR: enum 缺少 enum_values`);
      confidence = 0.3;
    } else {
      const values = schema.enum_values.map((v) => `'${v}'`).join(', ');
      lines.push(`export const ${name} = z.enum([${values}]);`);
      lines.push(`export type ${pascal(schema.name)} = z.infer<typeof ${name}>;`);
    }
  } else if (schema.kind === 'object') {
    lines.push(`export const ${name} = z.object({`);
    if (schema.fields) {
      for (const field of schema.fields) {
        const line = renderField(field, all, unsupported);
        if (line.unsupported) unsupported.push(line.unsupported);
        if (line.confidence < confidence) confidence = line.confidence;
        lines.push(`  ${line.code}`);
      }
    }
    lines.push(`})`);
    // .strict() 处理
    if (schema.strict) {
      lines[lines.length - 1] += '.strict()';
    }
    // extends 处理（z.object 不能直接 extends，用 .extend()）
    if (schema.extends) {
      lines[lines.length - 1] = lines[lines.length - 1].replace(
        `export const ${name} = z.object({`,
        `export const ${name} = ${schema.extends}Schema.extend({`,
      );
    }
    lines.push(`export type ${pascal(schema.name)} = z.infer<typeof ${name}>;`);
  } else {
    lines.push(`// 不支持的 kind: ${schema.kind}`);
    unsupported.push(`${schema.kind}`);
    confidence = 0.5;
  }

  return { code: lines.join('\n') + '\n', unsupported, confidence };
}

function renderField(
  field: FieldMetaInternal,
  all: Map<string, SchemaMetaInternal>,
  unsupported: string[],
): { code: string; zodExpr: string; unsupported?: string; confidence: number } {
  let zodExpr: string;
  let confidence = 1;

  switch (field.type) {
    case 'string':
      zodExpr = 'z.string()';
      if (field.min != null) zodExpr += `.min(${field.min})`;
      if (field.max != null) zodExpr += `.max(${field.max})`;
      break;
    case 'number':
      zodExpr = 'z.number()';
      if (field.min_value != null) zodExpr += `.min(${field.min_value})`;
      if (field.max_value != null) zodExpr += `.max(${field.max_value})`;
      // 整数约束启发：min_value >= 0 + 描述含"页码/数量/版本"则 .int()
      if (field.min_value != null && field.min_value >= 0 && /page|size|total|version|count/i.test(field.name)) {
        zodExpr += '.int()';
      }
      break;
    case 'boolean':
      zodExpr = 'z.boolean()';
      break;
    case 'uuid':
      zodExpr = 'z.string().uuid()';
      break;
    case 'datetime':
      zodExpr = 'z.string().datetime()';
      break;
    case 'email':
      zodExpr = 'z.string().email()';
      break;
    case 'enum':
      if (field.enum_values && field.enum_values.length) {
        const values = field.enum_values.map((v) => `'${v}'`).join(', ');
        zodExpr = `z.enum([${values}])`;
      } else if (field.enum_values_ref) {
        const refSchema = all.get(field.enum_values_ref);
        if (refSchema?.enum_values?.length) {
          // 直接引用另一 schema（保证 SSOT）
          zodExpr = `${field.enum_values_ref}Schema`;
        } else {
          zodExpr = `z.enum([]) // ERROR: enum_values_ref "${field.enum_values_ref}" 未找到`;
          confidence = 0.3;
        }
      } else {
        zodExpr = 'z.enum([]) // ERROR: enum 字段缺 enum_values / enum_values_ref';
        confidence = 0.3;
      }
      break;
    case 'array':
      if (field.items) {
        const inner = renderField(field.items as FieldMetaInternal, all, unsupported);
        if (inner.unsupported) unsupported.push(inner.unsupported);
        zodExpr = `z.array(${inner.zodExpr})`;
      } else {
        zodExpr = 'z.array(z.unknown()) // WARNING: array 缺 items';
        confidence = 0.6;
      }
      break;
    case 'ref':
      if (field.ref) {
        zodExpr = `${field.ref}Schema`;
      } else {
        zodExpr = 'z.unknown() // ERROR: ref 字段缺 ref';
        confidence = 0.3;
      }
      break;
    default:
      zodExpr = `z.unknown() // 不支持的类型: ${field.type}`;
      unsupported.push(field.type);
      confidence = 0.5;
  }

  // nullable / optional
  if (field.nullable) zodExpr += '.nullable()';
  if (field.optional) zodExpr += '.optional()';
  if (field.default != null) {
    const def = typeof field.default === 'string' ? `'${field.default}'` : String(field.default);
    zodExpr += `.default(${def})`;
  }

  return {
    code: `${field.name}: ${zodExpr},`,
    zodExpr,
    confidence,
  };
}

function collectDeps(
  schema: SchemaMetaInternal,
  all: Map<string, SchemaMetaInternal>,
): Set<string> {
  const deps = new Set<string>();
  if (schema.extends) deps.add(schema.extends);
  for (const f of schema.fields ?? []) {
    const field = f as FieldMetaInternal;
    if (field.enum_values_ref) deps.add(field.enum_values_ref);
    if (field.type === 'ref' && field.ref) deps.add(field.ref);
    if (field.type === 'array' && field.items) {
      const inner = field.items as FieldMetaInternal;
      if (inner.type === 'ref' && inner.ref) deps.add(inner.ref);
      if (inner.enum_values_ref) deps.add(inner.enum_values_ref);
    }
  }
  // 自身不算依赖
  deps.delete(schema.name);
  return deps;
}

function renderIndex(names: string[]): string {
  const lines: string[] = [];
  lines.push(`// AUTO-GENERATED by Zod renderer. DO NOT EDIT.`);
  lines.push('');
  for (const name of names) {
    lines.push(`export * from './${name}';`);
  }
  return lines.join('\n') + '\n';
}

function pascal(name: string): string {
  // snake_case → PascalCase
  return name
    .split(/[_-]/)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('');
}

const __dirname = dirname(fileURLToPath(import.meta.url));

function findMetaFiles(dir: string): string[] {
  // 候选 samples 路径：
  //   1. <renderer_src_dir>/../samples  —— 约定位置（与 renderer 同一 contract 父目录下）
  //   2. <out_dir>/../samples             —— 回退，兼容 out_dir 紧邻 samples 的旧用法
  const candidates = [
    join(__dirname, '..', 'samples'),
    join(dir, '..', 'samples'),
  ];
  for (const samplesDir of candidates) {
    try {
      return readdirSync(samplesDir)
        .filter((f: string) => f.endsWith('.meta.yaml'))
        .map((f: string) => join(samplesDir, f));
    } catch {
      continue;
    }
  }
  return [];
}
