// adapters/contract/pydantic/renderer.ts —— Pydantic 契约渲染器
// P0-2 产出：把契约元模型 (YAML) 渲染为 Pydantic schema (Python)。
//
// 覆盖类型映射：
//   string → str
//   number → int (整数场景) / float
//   boolean → bool
//   uuid → UUID
//   datetime → datetime
//   email → EmailStr (pydantic[email])
//   enum → Enum
//   array → List[items]
//   ref → 引用另一 schema 类名

import { readFileSync, readdirSync } from 'node:fs';
import { load as parseYaml } from 'js-yaml';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import type {
  ContractSchemaMeta,
  ContractFieldMeta,
  RenderContractInput,
  RenderContractResult,
  WriteOp,
  Confidence,
} from '../../../spi/adapter.js';

interface FieldMetaInternal extends ContractFieldMeta {
  enum_values_ref?: string;
  ref?: string;
}

interface SchemaMetaInternal extends ContractSchemaMeta {
  fields?: FieldMetaInternal[];
}

interface MetaFile {
  schemas: SchemaMetaInternal[];
}

export async function renderContract(input: RenderContractInput): Promise<RenderContractResult> {
  const metaFiles = findMetaFiles(input.out_dir);
  const allSchemas = new Map<string, SchemaMetaInternal>();
  for (const f of metaFiles) {
    const parsed = parseYaml(readFileSync(f, 'utf8')) as MetaFile;
    for (const s of parsed.schemas ?? []) {
      allSchemas.set(s.name, s);
    }
  }
  for (const s of input.schemas as SchemaMetaInternal[]) {
    allSchemas.set(s.name, s);
  }

  const writes: WriteOp[] = [];
  const unsupported: string[] = [];
  let confidence: Confidence = 1;

  for (const schema of allSchemas.values()) {
    const { code, unsupported: schemaUnsupported, confidence: schemaConf } = renderSchema(schema, allSchemas);
    if (schemaUnsupported.length) unsupported.push(...schemaUnsupported);
    confidence = Math.min(confidence, schemaConf);
    writes.push({
      path: join(input.out_dir, 'rendered', 'pydantic', `${snake(schema.name)}.py`),
      content: code,
      is_new: true,
      reason: `P0-2 Pydantic 渲染：${schema.name}`,
    });
  }

  const indexCode = renderIndex([...allSchemas.keys()]);
  writes.push({
    path: join(input.out_dir, 'rendered', 'pydantic', '__init__.py'),
    content: indexCode,
    is_new: true,
    reason: 'P0-2 Pydantic 渲染：聚合导出',
  });

  return { writes, confidence, unsupported_types: [...new Set(unsupported)] };
}

function renderSchema(
  schema: SchemaMetaInternal,
  all: Map<string, SchemaMetaInternal>,
): { code: string; unsupported: string[]; confidence: number } {
  const lines: string[] = [];
  const unsupported: string[] = [];
  let confidence = 1;

  // 头部注释
  lines.push(`# AUTO-GENERATED by Pydantic renderer. DO NOT EDIT.`);
  lines.push(`# Source: contract meta model (${schema.name})`);
  if (schema.description) {
    for (const line of schema.description.split('\n')) {
      lines.push(`# ${line}`);
    }
  }
  lines.push('');
  lines.push(`from __future__ import annotations`);
  lines.push('');
  lines.push(`from pydantic import BaseModel, EmailStr, Field`);
  lines.push(`from typing import Optional, List, Literal`);
  lines.push(`from uuid import UUID`);
  lines.push(`from datetime import datetime`);
  // 依赖引用
  const deps = collectDeps(schema, all);
  if (deps.size > 0) {
    lines.push('');
    for (const dep of deps) {
      lines.push(`from .${snake(dep)} import ${pascal(dep)}Schema`);
    }
  }
  lines.push('');

  const className = `${pascal(schema.name)}Schema`;

  if (schema.kind === 'enum') {
    if (!schema.enum_values?.length) {
      lines.push(`${className} = Literal[None]  # ERROR: enum 缺少 enum_values`);
      confidence = 0.3;
    } else {
      const values = schema.enum_values.map((v) => `"${v}"`).join(', ');
      lines.push(`${className} = Literal[${values}]`);
    }
  } else if (schema.kind === 'object') {
    lines.push(`class ${className}(BaseModel):`);
    if (schema.description) {
      lines.push(`    """${schema.description.split('\n')[0]}"""`);
    }
    // strict 等价：extra='forbid'
    if (schema.strict) {
      lines.push(`    model_config = {"extra": "forbid"}`);
    }
    if (!schema.fields?.length) {
      lines.push(`    pass`);
    } else {
      for (const field of schema.fields) {
        const line = renderField(field, all, unsupported);
        if (line.unsupported) unsupported.push(line.unsupported);
        if (line.confidence < confidence) confidence = line.confidence;
        lines.push(`    ${line.code}`);
      }
    }
    // extends 处理：用多继承
    if (schema.extends) {
      lines[lines.length - 1] = lines[lines.length - 1].replace(
        `class ${className}(BaseModel):`,
        `class ${className}(${pascal(schema.extends)}Schema):`,
      );
    }
  } else {
    lines.push(`# 不支持的 kind: ${schema.kind}`);
    unsupported.push(`${schema.kind}`);
    confidence = 0.5;
  }

  return { code: lines.join('\n') + '\n', unsupported, confidence };
}

function renderField(
  field: FieldMetaInternal,
  all: Map<string, SchemaMetaInternal>,
  unsupported: string[],
): { code: string; pyType: string; unsupported?: string; confidence: number } {
  let pyType: string;
  let confidence = 1;
  let fieldInfo = '';

  switch (field.type) {
    case 'string':
      pyType = 'str';
      if (field.min != null || field.max != null) {
        const min = field.min ?? 0;
        const max = field.max ?? '...';
        fieldInfo = ` = Field(min_length=${min}, max_length=${max})`;
      }
      break;
    case 'number':
      pyType = /page|size|total|version|count/i.test(field.name) ? 'int' : 'float';
      if (field.min_value != null) fieldInfo += `, ge=${field.min_value}`;
      if (field.max_value != null) fieldInfo += `, le=${field.max_value}`;
      if (fieldInfo) fieldInfo = ` = Field(${fieldInfo.slice(2)})`;
      break;
    case 'boolean':
      pyType = 'bool';
      break;
    case 'uuid':
      pyType = 'UUID';
      break;
    case 'datetime':
      pyType = 'datetime';
      break;
    case 'email':
      pyType = 'EmailStr';
      break;
    case 'enum':
      if (field.enum_values && field.enum_values.length) {
        const values = field.enum_values.map((v) => `"${v}"`).join(', ');
        pyType = `Literal[${values}]`;
      } else if (field.enum_values_ref) {
        pyType = `${pascal(field.enum_values_ref)}Schema`;
      } else {
        pyType = 'Any';
        unsupported.push('enum-without-values');
        confidence = 0.3;
      }
      break;
    case 'array':
      if (field.items) {
        const inner = renderField(field.items as FieldMetaInternal, all, unsupported);
        if (inner.unsupported) unsupported.push(inner.unsupported);
        pyType = `List[${inner.pyType}]`;
      } else {
        pyType = 'List[Any]';
        confidence = 0.6;
      }
      break;
    case 'ref':
      if (field.ref) {
        pyType = pascal(field.ref) + 'Schema';
      } else {
        pyType = 'Any';
        confidence = 0.3;
      }
      break;
    default:
      pyType = 'Any';
      unsupported.push(field.type);
      confidence = 0.5;
  }

  // nullable / optional
  if (field.nullable || field.optional) {
    pyType = `Optional[${pyType}]`;
  }
  if (field.default != null) {
    const def = typeof field.default === 'string' ? `"${field.default}"` : String(field.default);
    fieldInfo += ` = ${def}`;
  } else if (field.optional && !fieldInfo) {
    fieldInfo = ' = None';
  }

  return {
    code: `${field.name}: ${pyType}${fieldInfo}`,
    pyType,
    confidence,
  };
}

function collectDeps(
  schema: SchemaMetaInternal,
  all: Map<string, SchemaMetaInternal>,
): Set<string> {
  const deps = new Set<string>();
  if (schema.extends) deps.add(schema.extends);
  for (const f of schema.fields ?? []) {
    const field = f as FieldMetaInternal;
    if (field.enum_values_ref) deps.add(field.enum_values_ref);
    if (field.type === 'ref' && field.ref) deps.add(field.ref);
    if (field.type === 'array' && field.items) {
      const inner = field.items as FieldMetaInternal;
      if (inner.type === 'ref' && inner.ref) deps.add(inner.ref);
      if (inner.enum_values_ref) deps.add(inner.enum_values_ref);
    }
  }
  deps.delete(schema.name);
  return deps;
}

function renderIndex(names: string[]): string {
  const lines: string[] = [];
  lines.push(`# AUTO-GENERATED by Pydantic renderer. DO NOT EDIT.`);
  lines.push('');
  for (const name of names) {
    lines.push(`from .${snake(name)} import ${pascal(name)}Schema`);
  }
  return lines.join('\n') + '\n';
}

function pascal(name: string): string {
  return name
    .split(/[_-]/)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('');
}

function snake(name: string): string {
  // PascalCase → snake_case
  return name
    .replace(/([A-Z])/g, '_$1')
    .toLowerCase()
    .replace(/^_/, '')
    .replace(/-/g, '_');
}

const __dirname = dirname(fileURLToPath(import.meta.url));

function findMetaFiles(dir: string): string[] {
  const candidates = [
    join(__dirname, '..', 'samples'),
    join(dir, '..', 'samples'),
  ];
  for (const samplesDir of candidates) {
    try {
      return readdirSync(samplesDir)
        .filter((f: string) => f.endsWith('.meta.yaml'))
        .map((f: string) => join(samplesDir, f));
    } catch {
      continue;
    }
  }
  return [];
}
